### ISSUE TITLE
现在有一个xml文件，怎么生成wav？

### ISSUE THREAD

**Issue by leeseean** [UlyssesWu/Sinsy#3]

**Comment by UlyssesWu** [comment]
`Sinsy.exe -x dic -m nitech_jp_song070_f001.htsvoice -o song.wav song070_f001_063.xml`

**Comment by leeseean** [comment]
> `Sinsy.exe -x dic -m nitech_jp_song070_f001.htsvoice -o song.wav song070_f001_063.xml`

这个生成的音频声音怪怪的，断断续续，执行命令的时候提示no language，可能我要的是中文或者英文歌词，这个命令只处理日语，所以导致出来的音频断断续续不能曲调

**Comment by leeseean** [comment]
@UlyssesWu

**Comment by UlyssesWu** [comment]
Sinsy is developed by Japanese researchers. "Yoko" (`nitech_jp_song070_f001.htsvoice`) is a Japanese voice model. And `dic` is a Japanese dictionary.

You can applied it to other languages like Chinese or English with your (self-designed) dictionary and voice models. To make them, you have to gain enough knowledge about HMM & HTS.  https://github.com/VOICeVIO/Sinsy/issues/1#issuecomment-553484678 is a good point to start. 

There are also some projects trying to make use of HTS/Sinsy in other languages, such as sinsy-remix, [Festival](http://www.cstr.ed.ac.uk/projects/festival/) etc. You can learn from them to get some inspiration.

**However if you have no aspiration for learning a lot (including math, English, signal-processing, coding in C/C++ etc.), Sinsy will be useless to you.** And you should just earn enough money to buy Vocaloid / CeVIO/ SynthV etc. Or use some easy tools like UTAU or DeepVocal, which (AFAIC) won't catch the future of Singing Synthesis.

For now I haven't seen any "aspiration" from you. Before you continue, I think you should learn the [story](https://www.zhihu.com/question/24747703) of Kanru Hua - the developer of SynthV. Although I'm not 100% with him, he did spent so much on achieving his dream since he was a junior school student. Since then he keeps learning these things (which I doubt you might give up in 3 days) and finally SynthV is there. 

**Stop asking questions and start learning if you want to be the next Kanru Hua.**
